- name: Install and run Certbot on Console server
  hosts: all
  become: yes
  vars_files:
  - env_vars.yml
  tasks:
  - name: Import EPEL GPG key
    rpm_key:
      state: present
      key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-8

  - name: Install EPEL release from official URL
    dnf:
      name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
      state: present

  - name: Install Certbot
    dnf:
      name: certbot
      state: present

  - name: Check if SSL certificate already exists
    stat:
      path: /etc/letsencrypt/live/{{ CONSOLE_DOMAIN }}/fullchain.pem
    register: cert_stat

  - name: Stop console service
    command: asctl console:stop
    register: stopped_console_result
    changed_when: "'Console: Stop... done' in stopped_console_result.stdout"

  - name: Stop apache service
    command: asctl apache:stop
    register: stopped_apache_result
    changed_when: "'Apache: Stop... done' in stopped_apache_result.stdout"

  - name: Generate SSL certificate using Certbot (standalone method)
    command: >
      certbot certonly --standalone --preferred-challenges http --domain {{ CONSOLE_DOMAIN }} --email {{ WEB_ADMIN_EMAIL }} --agree-tos --non-interactive
    when: not cert_stat.stat.exists and stopped_console_result is not failed and stopped_apache_result is not failed
    register: certbot_result
    changed_when: "'Congratulations' in certbot_result.stdout"

  - name: Backup existing cert
    copy:
      src: /opt/aspera/common/apache/conf/server.crt
      dest: /opt/aspera/common/apache/conf/server.crt.bak
      remote_src: yes

  - name: Backup existing key
    copy:
      src: /opt/aspera/common/apache/conf/server.key
      dest: /opt/aspera/common/apache/conf/server.key.bak
      remote_src: yes

  - name: Copy certbot cert
    copy:
      src: /etc/letsencrypt/live/{{ CONSOLE_DOMAIN }}/fullchain.pem
      dest: /opt/aspera/common/apache/conf/server.crt
      owner: root
      group: root
      mode: '0400'
      remote_src: yes
    when: certbot_result is defined or cert_stat.stat.exists

  - name: Copy certbot key
    copy:
      src: /etc/letsencrypt/live/{{ CONSOLE_DOMAIN }}/privkey.pem
      dest: /opt/aspera/common/apache/conf/server.key
      owner: root
      group: root
      mode: '0400'
      remote_src: yes
    when: certbot_result is defined or cert_stat.stat.exists

  - name: Start console service
    command: asctl console:start
    register: start_console_result

  - name: Start apache service
    command: asctl apache:start
    register: start_apache_result

  - name: Show start output
    debug:
      var: start_console_result.stdout

  - name: Show start output
    debug:
      var: start_apache_result.stdout

  - name: Show Certbot output
    debug:
      var: certbot_result
    when: certbot_result is defined
